arb-dir: lib/l10n
output-dir: lib/l10n/generated
template-arb-file: app_en.arb
output-localization-file: app.translation.g.dart
untranslated-messages-file: lib/l10n/untranslated/desired.json
synthetic-package: false
