name: devtoys
description: a flutter implements of microsoft devtoys.

publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0

  cupertino_icons: ^1.0.2
  fluent_ui: ^3.9.0
  archive: ^3.2.1
  dart_style: ^2.2.1
  uuid: ^3.0.6
  crypto: ^3.0.1
  flutter_svg: ^1.0.3
  window_manager: ^0.1.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/logo/1080x1080.webp
    - assets/logo/256x256.webp
    - assets/icons/Base64.svg
    - assets/icons/JsonFormatter.svg
    - assets/icons/dart.svg
    - assets/icons/Guid.svg
