name: alga
description: A powerful tool app for all developers.

publish_to: "none"
version: 0.3.2+12

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0

  # custom packages
  lorem_ipsum:
    path: ./packages/lorem_ipsum
  highlight_textspan:
    path: ./packages/highlight_textspan
  json_textfield:
    path: ./packages/json_textfield
  language_textfield:
    path: ./packages/language_textfield

  cupertino_icons: ^1.0.2
  archive: ^3.2.2
  dart_style: ^2.2.1
  uuid: ^3.0.6
  crypto: ^3.0.1
  flutter_svg: ^1.0.3
  window_manager: ^0.2.0
  yaml: ^3.1.0
  json2yaml: ^3.0.0
  flutter_markdown: ^0.6.9
  extended_text_field: ^10.0.0
  package_info_plus: ^1.4.0
  url_launcher: ^6.0.20
  animations: ^2.0.2
  flutter_riverpod: ^1.0.3
  hotkey_manager: ^0.1.6
  sass: ^1.49.9
  file_selector: ^0.8.4+1
  shelf_static: ^1.1.0
  flutter_highlight: ^0.7.0
  hive: ^2.0.6
  hive_flutter: ^1.1.0
  qr_flutter: ^4.0.0
  blurhash_dart: ^1.1.0
  flutter_blurhash: ^0.6.4
  image_picker: ^0.8.4+11
  device_info_plus: ^3.2.2
  network_info_plus: ^2.1.3
  flutter_js: ^0.5.0+6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  hive_generator: ^1.1.2
  build_runner: ^2.1.8

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/icons/
    - assets/logo/
