name: alga
description: a flutter implements of microsoft devtoys.

publish_to: "none"
version: 0.1.2+3

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0

  # custom packages
  lorem_ipsum:
    path: ./packages/lorem_ipsum
  json_textfield:
    path: ./packages/json_textfield
  language_textfield:
    path: ./packages/language_textfield

  cupertino_icons: ^1.0.2
  fluent_ui: ^3.9.1
  archive: ^3.2.1
  dart_style: ^2.2.1
  uuid: ^3.0.6
  crypto: ^3.0.1
  flutter_svg: ^1.0.3
  window_manager: ^0.1.9
  fluentui_system_icons: ^1.1.161
  yaml: ^3.1.0
  json2yaml: ^3.0.0
  flutter_markdown: ^0.6.9
  extended_text_field: ^10.0.0
  package_info_plus: ^1.4.0
  url_launcher: ^6.0.20

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/logo/1080x1080.webp
    - assets/logo/256x256.webp
    - assets/icons/
